// GENERATED by tool/encrypt_assets.dart -- do not edit by hand.
//
// Fingerprint of the plaintext question banks bundled with this build.
// SyncService re-imports from assets whenever this differs from the value it
// recorded on its last import, so a build shipping corrected questions actually
// reaches people who already have the app installed.
const String kBundledContentVersion = '81570f01b839bf71';
