import 'dart:convert';
import 'dart:io';
import 'package:crypto/crypto.dart';
import 'package:questionx/utils/crypto.dart';

/// Build-time encryptor. Reads plaintext question banks (local source of truth)
/// and writes AES-encrypted `*.json.enc` that get bundled into the app.
///
/// Also stamps `lib/content_version.dart` with a fingerprint of the PLAINTEXT
/// banks. SyncService compares that constant against the value it stored on the
/// last import and re-reads the bundled banks whenever it changes.
///
/// Why this exists: the app only imported from assets when the database was
/// empty, so shipping an APK with corrected questions did nothing for anyone who
/// already had it installed — their database kept the old text until an OTA
/// release happened to fire. NEET_2024_Zoo_184 was fixed in v1.7.6 and still
/// showed the old, broken text on an upgraded install.
///
/// Fingerprinting the plaintext (not the .enc) is deliberate: encryption uses a
/// fresh random IV every run, so the .enc bytes differ on every invocation even
/// when nothing changed, which would force a pointless re-import each build.
///
/// Run: `dart run tool/encrypt_assets.dart`
void main() {
  final plaintexts = <String>[];
  for (final f in const ['neet', 'jee']) {
    final src = File('assets/$f.json');
    if (!src.existsSync()) {
      stderr.writeln('missing assets/$f.json');
      exit(1);
    }
    final plain = src.readAsStringSync();
    final bytes = DataCrypto.encryptString(plain);
    File('assets/$f.json.enc').writeAsBytesSync(bytes);
    final back = DataCrypto.decryptBytes(
        File('assets/$f.json.enc').readAsBytesSync());
    if (back != plain) {
      stderr.writeln('ROUND-TRIP FAILED for $f');
      exit(1);
    }
    plaintexts.add(plain);
    stdout.writeln('encrypted $f.json -> $f.json.enc '
        '(${bytes.length} bytes, round-trip OK)');
  }

  final fingerprint =
      sha256.convert(utf8.encode(plaintexts.join())).toString().substring(0, 16);
  final out = File('lib/content_version.dart');
  final next = '''
// GENERATED by tool/encrypt_assets.dart -- do not edit by hand.
//
// Fingerprint of the plaintext question banks bundled with this build.
// SyncService re-imports from assets whenever this differs from the value it
// recorded on its last import, so a build shipping corrected questions actually
// reaches people who already have the app installed.
const String kBundledContentVersion = '$fingerprint';
''';
  if (!out.existsSync() || out.readAsStringSync() != next) {
    out.writeAsStringSync(next);
    stdout.writeln('stamped lib/content_version.dart -> $fingerprint');
  } else {
    stdout.writeln('content unchanged ($fingerprint)');
  }
}
